

services:
  web:
    build: .
    container_name: django_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
      - ./media:/app/media
    ports:
      - "8000:8000" 
    env_file:
      - .env 
    depends_on:
      - db

  db:
      image: mysql:8.0
      container_name: mysql_db
      restart: always
      environment:
        MYSQL_DATABASE: ${DB_NAME}
        MYSQL_USER: ${DB_USER}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      ports:
        - "3306:3306"
      volumes:
        - db_data:/var/lib/mysql

volumes:
  db_data: