# Generated by Django 5.2.6 on 2025-12-11 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='cuit',
            field=models.CharField(max_length=20, null=True, unique=True),
        ),
    ]
