# Generated by Django 5.2.6 on 2025-12-11 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_cuit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='razon_social',
            field=models.CharField(max_length=100, null=True, unique=True),
        ),
    ]
